# Q3 Using Scikit-Learn

In [1]:
import numpy as np
import pandas as pd
import time
import gc
from sklearn.model_selection import cross_val_score, GridSearchCV, cross_validate, train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, normalize
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer

In [2]:
# Change to your GA Tech ID
ga_id = 'pkaundinya3'
# Requires a print() statement do not modify below print statement
print(ga_id)

pkaundinya3


# Q3.1 Data Import and Cleansing Setup

In [3]:
# XXX
# TODO: Read in all the data. Replace the 'xxx' with the path to the data set. We've started this for you. 
# XXX

# -------------------------------
# ADD CODE HERE
data = pd.read_csv('pulsar_stars.csv')
# -------------------------------

# XXX
# TODO: Separate out the x_data and y_data. We've started this for you.
# XXX

# -------------------------------
# ADD CODE HERE
x_data = data.loc[:,['X1','X2','X3','X4','X5','X6','X7','X8']]
y_data = data.loc[:,'y']
# -------------------------------


In [4]:
# XXX
# TODO: Split 70% of the data into training and 30% into test sets. Call them x_train, x_test, y_train and y_test.
# Use the train_test_split method in sklearn with the parameter 'shuffle' set to true and the 'random_state' 
# set to 614.
# 

# -------------------------------
# ADD CODE HERE
# -------------------------------
x_train, x_test, y_train,y_test = train_test_split(x_data,y_data,shuffle=True,random_state=614)

# Q3.2 Linear Regression 

In [5]:
# XXX
# TODO: Create a LinearRegression classifier and train it.
# XXX

# -------------------------------
# ADD CODE HERE
lin_model = LinearRegression(n_jobs=-1)
lin_model.fit(x_train,y_train)
# -------------------------------

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=-1, normalize=False)

In [6]:
# XXX
# TODO: Test its accuracy (on the training set) using the accuracy_score method.
# Note: Round the output values greater than or equal to 0.5 to 1 and those less than 0.5 to 0. You can use any method that satisfies the requriements.
# XXX

# -------------------------------
# ADD CODE HERE
lin_pred_train = np.rint(lin_model.predict(x_train))
print(accuracy_score(y_train,lin_pred_train))
# -------------------------------

0.971615883185577


In [7]:
# XXX
# TODO: Test its accuracy (on the testing set) using the accuracy_score method.
# Note: Round the output values greater than or equal to 0.5 to 1 and those less than 0.5 to 0. You can use any method that satisfies the requriements.
# XXX

# -------------------------------
# ADD CODE HERE
lin_pred_test = np.rint(lin_model.predict(x_test))
print(accuracy_score(y_test,lin_pred_test))
# -------------------------------

0.9678212290502793


# Q3.3 Random Forest Classifier

In [8]:
# XXX
# TODO: Create a RandomForestClassifier and train it.
# Set 'random_state' to 614
# XXX

# -------------------------------
# ADD CODE HERE
rf_model = RandomForestClassifier(random_state = 614,n_jobs=-1)
rf_model.fit(x_train,y_train)
# -------------------------------

C:\Users\Prathik\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=-1,
                       oob_score=False, random_state=614, verbose=0,
                       warm_start=False)

In [9]:
# XXX
# TODO: Test its accuracy on the training set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
rf_pred_train = rf_model.predict(x_train)
print(accuracy_score(y_train,rf_pred_train))
# -------------------------------

0.9963495492810847


In [10]:
# XXX
# TODO: Test its accuracy on the test set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
rf_pred_test = rf_model.predict(x_test)
print(accuracy_score(y_test,rf_pred_test))
# -------------------------------

0.9769832402234637


## Q3.3.1 Feature Importance

In [11]:
# XXX
# TODO: Determine the feature importance as evaluated by the Random Forest Classifier.
# XXX

# -------------------------------
# ADD CODE HERE
print(rf_model.feature_importances_)
# -------------------------------

[0.35951752 0.06134451 0.27238298 0.10875699 0.07179917 0.04190842
 0.05964191 0.02464849]


In [12]:
# XXX
# TODO: Sort them in the descending order and print the feature numbers[0 to ...].
#       Hint: There is a direct function available in sklearn to achieve this. Also checkout argsort() function in Python.
# XXX

# -------------------------------
# ADD CODE HERE
print(np.argsort(rf_model.feature_importances_))
# -------------------------------

[7 5 6 1 4 3 2 0]


## Q3.3.2 Hyper-parameter Tuning

In [13]:
# XXX
# TODO: Tune the hyper-parameters 'n_estimators' and 'max_depth'.
# 'n_estimators': [4, 16, 256]
# 'max_depth': [2, 8, 16]
# XXX

# -------------------------------
# ADD CODE HERE
param_grid_rf = {'n_estimators':[4, 16, 256],'max_depth':[2, 8, 16]}
hptune_rf = GridSearchCV(rf_model,param_grid_rf,n_jobs=-1,verbose=5)
hptune_rf.fit(x_train,y_train)
# -------------------------------

Fitting 3 folds for each of 9 candidates, totalling 27 fits


C:\Users\Prathik\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    4.2s
[Parallel(n_jobs=-1)]: Done  27 out of  27 | elapsed:   12.2s finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=10, n_jobs=-1,
                                              oob_score=False, random_state=614,
                                              verbose=0, warm_start=False),
             iid='warn', n_jobs=-1,
             param_grid={'ma

In [14]:
# XXX
# TODO: Get the best params, using .best_params_
# XXX

# -------------------------------
# ADD CODE HERE
print(hptune_rf.best_params_)
# -------------------------------

{'max_depth': 16, 'n_estimators': 256}


In [15]:
# XXX
# TODO: Get the best score, using .best_score_.
# XXX

# -------------------------------
# ADD CODE HERE
print(hptune_rf.best_score_)
# -------------------------------

0.980257766520152


# Q3.4 Support Vector Machine

## Q3.4.1 Pre-process

In [16]:
# XXX
# TODO: Pre-process the data to standardize it, otherwise the grid search will take much longer.
# XXX

# -------------------------------
# ADD CODE HERE
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x_data)
# -------------------------------

## Q3.4.2 Classification

In [17]:
# XXX
# TODO: Create a SVC classifier and train it.
# XXX

# -------------------------------
# ADD CODE HERE
svc_model = SVC(verbose=True)
svc_model.fit(x_train,y_train)
# -------------------------------

[LibSVM]

C:\Users\Prathik\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=True)

In [18]:
# XXX
# TODO: Test its accuracy on the training set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
svc_pred_train = svc_model.predict(x_train)
print(accuracy_score(y_train,svc_pred_train))
# -------------------------------

0.9937420844818595


In [19]:
# XXX
# TODO: Test its accuracy on the test set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
svc_pred_test = svc_model.predict(x_test)
print(accuracy_score(y_test,svc_pred_test))
# -------------------------------

0.9077094972067039


## Q3.4.3 Hyper-parameter Tuning

In [20]:
# XXX
# TODO: Tune the hyper-parameters 'C' and 'kernel' (use rbf and linear).
# 'kernel':('linear', 'rbf') 
# 'C':[0.01, 0.1, 1.0]
# XXX

# -------------------------------
# ADD CODE HERE
param_grid_svc = {'kernel':['linear', 'rbf'],'C':[0.01, 0.1, 1.0]}
hptune_svc = GridSearchCV(svc_model,param_grid_svc,n_jobs=-1,verbose=5,return_train_score=True)
hptune_svc.fit(x_train,y_train)
# -------------------------------

Fitting 3 folds for each of 6 candidates, totalling 18 fits


C:\Users\Prathik\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:   32.1s
[Parallel(n_jobs=-1)]: Done  15 out of  18 | elapsed:   57.9s remaining:   11.5s
[Parallel(n_jobs=-1)]: Done  18 out of  18 | elapsed:  1.2min finished


[LibSVM]

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=True),
             iid='warn', n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1.0], 'kernel': ['linear', 'rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
             scoring=None, verbose=5)

In [21]:
# XXX
# TODO: Get the best score, using .best_score_.
# Note: Set n_jobs=-1 and return_train_score=True
# XXX

# -------------------------------
# ADD CODE HERE
print(hptune_svc.best_score_)
# -------------------------------

0.9799597705430977


In [22]:
# XXX
# TODO: Calculate the training and test set accuracy values after hyperparameter tuning and standardization. 
# XXX

# -------------------------------
# ADD CODE HERE
print(hptune_svc.score(x_train,y_train))
print(hptune_svc.score(x_test,y_test))
# -------------------------------

0.9798852715488341
0.9769832402234637


In [23]:
# XXX
# TODO: Test its accuracy (on the training set) using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
hptune_svc_pred_train = hptune_svc.predict(x_train)
print(accuracy_score(y_train,hptune_svc_pred_train))
# -------------------------------

0.9798852715488341


In [24]:
# XXX
# TODO: Test its accuracy (on the test set) using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
hptune_svc_pred_test = hptune_svc.predict(x_test)
print(accuracy_score(y_test,hptune_svc_pred_test))
# -------------------------------

0.9769832402234637


## Q3.4.4 Cross Validation Results 

In [25]:
# XXX
# TODO: Get the rank test score for all hyperparameter values that you obtained in Q3.4.3. The 
# GridSearchCV class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX

# -------------------------------
# ADD CODE HERE
print(hptune_svc.cv_results_['rank_test_score'])
# -------------------------------

[3 5 2 5 1 4]


In [26]:
# XXX
# TODO: Get the mean testing score for all of hyperparameter values that you obtained in Q3.4.3. The 
# GridSearchCV class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX
# -------------------------------
# ADD CODE HERE
print(hptune_svc.cv_results_['mean_test_score'])
# -------------------------------

[0.97638382 0.90918573 0.97891678 0.90918573 0.97995977 0.90978172]


# Q3.5 PCA

In [27]:
# XXX
# TODO: Perform dimensionality reduction of the data using PCA.
#       Set parameters n_component to 8 and svd_solver to 'full'. Keep other parameters at their default value.
# XXX

# NOTE: Use the full x data set for this section 'x_data'

# -------------------------------
# ADD CODE HERE
# You should see an output here of PCA(copy=True....)
pca = PCA(n_components=8, svd_solver='full')
pca.fit(x_data)
# -------------------------------

PCA(copy=True, iterated_power='auto', n_components=8, random_state=None,
    svd_solver='full', tol=0.0, whiten=False)

In [28]:
# XXX
# TODO: Get percentage of variance explained by each of the selected components
# XXX

# -------------------------------
# ADD CODE HERE
print(pca.explained_variance_ratio_)
# -------------------------------

[8.71053041e-01 7.81934383e-02 4.11562290e-02 6.15967691e-03
 2.43717952e-03 9.58578490e-04 3.90570992e-05 2.79968662e-06]


In [29]:
# XXX
# TODO: Get the singular values corresponding to each of the selected components.
# XXX

# -------------------------------
# ADD CODE HERE
print(pca.singular_values_)
# -------------------------------

[14430.28004546  4323.5214088   3136.68022725  1213.47665361
   763.30168073   478.70316467    96.62788002    25.87063984]
